### ISSUE TITLE
Buff Juggernaut to T3.5 and Helltank Nerf/Rework

### ISSUE THREAD

**Issue by Azraeel** [LOUD-Community-Edition/LOUD-Community-Edition#123]

**Comment by Azraeel** [comment]
@rajderks assigned.

**Comment by Azraeel** [comment]
Helltank needs a nerf imo it just deals too much DPS with too much HP. Maybe glass cannon?

**Comment by Kami-Interface** [comment]
@Azraeel would be nice to consider these changes before spending time balancing the Helltank and Juggernaut
https://github.com/LOUD-Community-Edition/LOUD-Community-Edition/discussions/127
