### ISSUE TITLE
Fix Hitbox Issues on Various Units

### ISSUE THREAD

**Issue by Azraeel** [LOUD-Community-Edition/LOUD-Community-Edition#125]
Specifically Laser Units suffers heavily against certain units
Examples:
T4 Athusil

**Comment by rajderks** [comment]
SACUS still have one bone outside of the hitbox right?

**Comment by Azraeel** [comment]
That was fixed

**Comment by PurpleMossClump** [comment]
Certain small units also have this issue, with even weapons as precise as lasers consistently firing over or in front of them.
Aeon T1 scouts
Cybran T1 Moles, even when revealed, can still evade fire with their poor hitbox

**Comment by Azraeel** [comment]
@PurpleMossClump @Kami-Interface @loudpatches @rajderks 

Id been interested in having a round table and gathering every single known/documented unit that has a target bone or hitbox issue and what types of weapons they have the issue with.
