### ISSUE TITLE
aeon t1/t2 static artillery bugged

### ISSUE THREAD

**Issue by loudpatches** [LOUD-Community-Edition/LOUD-Community-Edition#158]
overshoots across the map

**Comment by rajderks** [comment]
I'll take a stab 🔪

**Comment by rajderks** [comment]
Can't reproduce. (although did observe in a game with spoon)
Charsomething and Miasma artillery work fine in sandbox.

Loud 7.10
LCE 1.31
M28 127

**Comment by loudpatches** [comment]
IIRC, in the t1 arty, I was just letting them fire and they were missing. I think ground fire or microing them may have worked;  no idea.
