### ISSUE TITLE
Dev Process Should Depend on Upstream Release (Not Churning Master Branch)

### ISSUE THREAD

**Issue by loudpatches** [LOUD-Community-Edition/LOUD-Community-Edition#19]
As exposed earlier, developing against the upstream master branch is a bad idea.  Right now, they aren't using tagging, so versioning/release is implicit in the commits.  There is no dev branch or tagged release model, so master = dev.  Given the primarily solo dev process and potential widespread (unforeseen) changes that are introduced, anything downstream (like this repo) is pretty vulnerable to breakage.  E.g. name changes, deleting files, refactoring stuff.

Local development needs to use a tagged release of the upstream mod (or alternately, just a specific commit / branch) instead of just pulling from whatever commit upstream happens to be on.

**Comment by loudpatches** [comment]
Release 7.09 is from ca1aa6664355715a58a0725620460359568ab96b on the git-loud repo.
You can tag this on your local git repo (or checkout the commit and branch it) if you want to be consistent with the most recent release on the updater.

**Comment by Azraeel** [comment]
Fixed & Noted
