### ISSUE TITLE
Remove emergency drops

### ISSUE THREAD

**Issue by Kami-Interface** [LOUD-Community-Edition/LOUD-Community-Edition#21]

**Comment by loudpatches** [comment]
Suspect that [IssueStop](https://github.com/LOUD-Project/Git-LOUD/blame/master/gamedata/lua/lua/AI/Transportutilities.lua#L2596) already induces delay commensurate with UI order.  If so, then that likely precludes the unit flinging case where

- at tick t, in worst case, 
- transport has 1 HP
- move thread from WatchTransportTravel happens to detect it at t, and decided to immediately initiate old drop sequence.
- unit unloading technically initiates giving iframes
- sim clock advances to t + 1
- transport dies, but units survive and are flung to the ground

If there is a commensurate UI delay now included in the IssueStop (5 ticks IIRC), then the above scenario should be unlikely (assuming transport incurs damage over the 5 ticks and dies before unloading).  It remains to be seen if this is sufficient though in practice.  If not, look at either more delays or other options to detect death in transit and overrule the iframes.

**Comment by Azraeel** [comment]
are we still interested in doing this @loudpatches i imagine so just asking.

**Comment by Azraeel** [comment]
I was doing some testing, LOUD's late game air without Air Spawn waves is already so pathetic i can't imagine a universe where he poses any real threat late game without lol

**Comment by loudpatches** [comment]
I haven't played LOUD  AI in weeks; no idea if it matters.
