### ISSUE TITLE
Double initial storage for commander 

### ISSUE THREAD

**Issue by AmericanSniper** [LOUD-Community-Edition/LOUD-Community-Edition#40]
By doing this, we can fix the initial stutter that happens in most openings on low-reclaim maps (major maps in the game). In the first two minutes of the game, you're just watching your commander execute five orders, which feels dull. In LOUD, the factory build rate is increased by 100%, which is why you quickly run out of resources when building engineers. To address this, the game mechanic provides you with +4,294,967,295 mass and energy in first tick of the simulation, filling any available storage. (I could be wrong about that).

By doubling the storage, we can eliminate the frustrating 'noob trap' where you have to stop production after building three engineers until you've completed four mexes and four power generators.
You can find these line in commander bp files, example:

        StorageEnergy = 5000, -> 10000,
        StorageMass = 650, -> 1300,
        
Thanks.

**Comment by Azraeel** [comment]
I will look at it and test it for sure, the opening right now is very scuffed for sure.

**Comment by Azraeel** [comment]
@loudpatches @Kami-Interface whats ur opinion this topic

**Comment by PurpleMossClump** [comment]
Double is too much. Would be far too easy to skip T1 entirely and go straight into T2 mexes at the beginning of the game.

**Comment by loudpatches** [comment]
I am used to the opening power curve.  Could be a mutator mod though.

**Comment by Kami-Interface** [comment]
At most a 20% increase of base mass+power. We can also leave it alone. If you're going to tweak the cost to factories or the movement speed of engineers/ACU then those things will also have a major impact on starting BO. I suggest waiting with this until the ACU changes are done
