### ISSUE TITLE
Seraphim T1 Land Overall

### ISSUE THREAD

**Issue by AmericanSniper** [LOUD-Community-Edition/LOUD-Community-Edition#46]
im about to bring my very passion to seraphim t1, IMO completely, 
[Sera T1.zip](https://github.com/user-attachments/files/16921417/Sera.T1.zip)
this could be start of discussion, othazyne slowest - range equal to thaam, 
yenhawoh 400m range, quadriple energy cost of thaam, artillery does less damage and less range, and are equal to thaam by mass, 
selen ia-istle, and engineer are copied from FAF.
only protector bot won't be affected by me WHY? i can't, i surrender, please help.

**Comment by Azraeel** [comment]
@Kami-Interface @loudpatches

**Comment by PurpleMossClump** [comment]
I'm not understanding the need for this to be done. 
If one faction has its T1 units changed, the other 3 also have to be changed as they should all be mostly functionally similar to each other at that stage so that no faction has any glaring advantage over another less than 10 minutes into the game.

**Comment by Kami-Interface** [comment]
I'm not gonna read through all the blueprints and compare against the values currently in use. Please format the changes in a separate document or in a comment here in Git. Example:

| Unit | Old value | New value |
|--------|--------|--------|
| Unit name 1 | 450 HP, 371 DPS, 0.067 Range | 470 HP, 320 DPS, 0.045 Range |
| Unit name 2 | 1500 HP, 600 DPS, 0.1 Range | 1200 HP, 550 DPS, 0.5 Range |/

I still think we should talk through which units we should get rid of, and which units need balance changes before actually spending time balancing units
