### ISSUE TITLE
Ahwassa (xsa0402) is not functioning properly

### ISSUE THREAD

**Issue by PurpleMossClump** [LOUD-Community-Edition/LOUD-Community-Edition#52]
Unit Ahwassa (xsa0402) experiencing issues with ground fire and attacking targets.

Unit will fly over target area without dropping payload sometimes. 

Values need to be adjusted to guarantee Unit will fire its weapon during a bombing run.

**Comment by PurpleMossClump** [comment]
If this is a matter of the unit's physics being abuseable when it is functional, imo it would be better for the unit to have some cheesiness than for it to be un-useable. 

If there's even a 10% chance that the unit won't fire its weapon, then it's just not even worth building.

**Comment by loudpatches** [comment]
related https://github.com/LOUD-Project/Git-LOUD/pull/99

**Comment by Azraeel** [comment]
will check this out later tonight
