### ISSUE TITLE
add version tag to ui

### ISSUE THREAD

**Issue by loudpatches** [LOUD-Community-Edition/LOUD-Community-Edition#54]
would be nice to know what version of LCE we are running.

**Comment by Azraeel** [comment]
@loudpatches assigned to you.

**Comment by rajderks** [comment]
Tried all sorts of paths but couldn't get this to work.

**Comment by loudpatches** [comment]
Wondering why original GPG author made everything local.  Looks like only one function can even be hooked.  So basically the intended API is to hook that one function, which closes over a bunch of local vars.

Hmm.

**Comment by loudpatches** [comment]
fixed in updater (thanks @rajderks
